# This workflow will build a Go project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.1

      - name: Install Go
        uses: actions/setup-go@v5.0.0
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - name: Setup GO env
        run: go env -w CGO_ENABLED=0

      - name: Build
        run: make build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist binaries
          path: |
            dist

      - name: Test
        run: make cover

      - name: Archive test results
        uses: actions/upload-artifact@v4
        with:
          name: test artifacts
          path: |
            coverage.*

